# Generated by Django 4.1.1 on 2022-09-12 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caringarage',
            old_name='nett_TO_mileage',
            new_name='next_TO_mileage',
        ),
    ]
