# Generated by Django 4.1.1 on 2022-09-12 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_nett_to_mileage_caringarage_next_to_mileage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Promotions',
            new_name='Promotion',
        ),
    ]
